apiVersion: v1
data:
  catalog.json: |-
    [
      {
        "name": "Grey Mug",
        "description": "This is a grey mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-plain.svg",
        "stock": 3261
      },
      {
        "name": "Orange Mug",
        "description": "This is a orange mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-orange.svg",
        "stock": 9667
      },
      {
        "name": "Yellow Mug",
        "description": "This is a yellow mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-yellow.svg",
        "stock": 5821
      },
      {
        "name": "Purple Mug",
        "description": "This is a purple mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-purple.svg",
        "stock": 7160
      },
      {
        "name": "Bordeaux Mug",
        "description": "This is a bordeaux mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-bordeaux.svg",
        "stock": 8183
      },
      {
        "name": "Turquoise Mug",
        "description": "This is a turquoise mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-turquoise.svg",
        "stock": 7389
      },
      {
        "name": "Darkpurple Mug",
        "description": "This is a darkpurple mug. Keeps you drinking coffee all day",
        "price": 3,
        "imgurl": "/static/static-mug-export-darkpurple.svg",
        "stock": 2309
      },
      {
        "name": "Grey Sticker",
        "description": "This is a grey sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-plain.svg",
        "stock": 8518
      },
      {
        "name": "Orange Sticker",
        "description": "This is a orange sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-orange.svg",
        "stock": 9006
      },
      {
        "name": "Yellow Sticker",
        "description": "This is a yellow sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-yellow.svg",
        "stock": 4968
      },
      {
        "name": "Purple Sticker",
        "description": "This is a purple sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-purple.svg",
        "stock": 8265
      },
      {
        "name": "Bordeaux Sticker",
        "description": "This is a bordeaux sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-bordeaux.svg",
        "stock": 4481
      },
      {
        "name": "Turquoise Sticker",
        "description": "This is a turquoise sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-turquoise.svg",
        "stock": 7106
      },
      {
        "name": "Darkpurple Sticker",
        "description": "This is a darkpurple sticker. Stick it everywhere!",
        "price": 1,
        "imgurl": "/static/static-sticker-export-darkpurple.svg",
        "stock": 2516
      },
      {
        "name": "Grey Shirt",
        "description": "This is a grey shirt. Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-plain.svg",
        "stock": 9809
      },
      {
        "name": "Orange Shirt",
        "description": "This is a orange shirt.  Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-orange.svg",
        "stock": 2083
      },
      {
        "name": "Yellow Shirt",
        "description": "This is a yellow shirt.  Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-yellow.svg",
        "stock": 6350
      },
      {
        "name": "Purple Shirt",
        "description": "This is a purple shirt.  Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-purple.svg",
        "stock": 9110
      },
      {
        "name": "Bordeaux Shirt",
        "description": "This is a bordeaux shirt.  Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-bordeaux.svg",
        "stock": 7535
      },
      {
        "name": "Turquoise Shirt",
        "description": "This is a turquoise shirt.  Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-turquoise.svg",
        "stock": 3481
      },
      {
        "name": "Darkpurple Shirt",
        "description": "This is a darkpurple shirt.  Wear it any time!",
        "price": 10,
        "imgurl": "/static/static-tshirt-export-darkpurple.svg",
        "stock": 9215
      }
    ]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: catalog-init
  labels:
    {{- include "k10app.labels" . | nindent 4 }}