apiVersion: v1
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }

      location /catalog {
        proxy_pass http://catalog/catalog;
      }
      location /user {
        proxy_pass http://basicuserservice/user;
      }
      location /order {
        proxy_pass http://order/order;
      }

      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
  labels:
    {{- include "k10app.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: router
    {{- include "k10app.labels" . | nindent 4 }}
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "k10app.labels" . | nindent 8 }}
        app: router
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginxconf
      volumes:
      - name: nginxconf
        configMap:
          name: nginx-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: router
    {{- include "k10app.labels" . | nindent 4 }}
  name:  router
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: router
  type: LoadBalancer
