apiVersion: v1
data:
  CATALOG_URL: ""
  USERS_URL: ""
  ORDERS_URL: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: frontend-configuration
  labels:
    {{- include "k10app.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    {{- include "k10app.labels" . | nindent 4 }}
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        {{- include "k10app.labels" . | nindent 8 }}
    spec:
      containers:
      - image: ghcr.io/k10app/frontend
        name: frontend
        resources: {}
        envFrom:
        - configMapRef:
            name: frontend-configuration
      imagePullSecrets:
      - name: regcred  
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    {{- include "k10app.labels" . | nindent 4 }}
  name:  frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
