apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: static
    {{- include "k10app.labels" . | nindent 4 }}     
  name: static
  namespace: k10app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: static
        {{- include "k10app.labels" . | nindent 8 }}        
    spec:
      containers:
      - image: ghcr.io/k10app/staticcache
        name: static
      imagePullSecrets:
      - name: regcred  
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: static
    {{- include "k10app.labels" . | nindent 4 }}     
  name:  static
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static
  type: LoadBalancer
