---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: k10app-sa
  namespace: k10app
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: k10app-sa
  namespace: k10app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: k10app-sa-k10app-sa
  namespace: k10app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k10app-sa
subjects:
- kind: ServiceAccount
  name: k10app-sa
  namespace: k10app
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: businit
  namespace: k10app
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ghcr.io/k10app/businit
        name: businit
        resources: {}
        env:
        - name: TARGET_NAMESPACE
          value: k10app
      restartPolicy: Never
      serviceAccountName: k10app-sa
      imagePullSecrets:
      - name: regcred  