apiVersion: v1
data:
  catalog: catalog
  bus: bus
  order: order
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: frontend-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace: k10app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/k10app/frontend
        name: frontend
        resources: {}
        envFrom:
        - configMapRef:
            name: frontend-configuration
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name:  frontend
  namespace: k10app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer
