apiVersion: v2
name: k10app
description: K10 Demo App

type: application

# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"

#converted from
#helm repo add bitnami https://charts.bitnami.com/bitnami
#helm install --namespace $NSK10  bitnami/mongodb  --set architecture="replicaset"
#helm install --namespace $NSK10 mysql bitnami/mysql --set auth.database="userdb"
#helm install --namespace $NSK10 postgres bitnami/postgresql

# To get versions, first add repo and then : helm search repo bitnami/postgresql
# To download dependency : helm dependency update

dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
- name: mongodb
  version: 13.x.x
  repository: https://charts.bitnami.com/bitnami
- name: mysql
  version: 9.x.x
  repository: https://charts.bitnami.com/bitnami



