# global
global:
  storageClass: ""
  

# Default values for k10app.
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: ""

routingPrefix: ""
serviceType: "ClusterIP"

imagePullSecrets: [{ "name": "regcred" }]

# helm subchart configs
mongodb:
  architecture: "replicaset"
  fullnameOverride: "mongo-mongodb"
  nameOverride: "mongo"
mysql:
  auth:
    database: "userdb"
  fullnameOverride: "mysql"
  nameOverride: "mysql"
postgresql:
  fullnameOverride: "postgres-postgresql"
  nameOverride: "postgresql"
